CRUD for Announcements #11
Web-Dev-x-Blueprint/cs554-final-project pull request #15
Opened 2024-12-11 19:04 UTC by RyanCamburn

Implemented #11 , left out Redis for future implementation

- Made Data files for 
1. create
2. getAll
3. getById
4. update
5. delete

- Made API routes (Located in pages/api/announcements) 
1. create  
2. getAll
3. update
4. delete

I didn't make one for getById

- Made components to Test CRUD
- You have to add the component to a page to use (I didn't want to dirty Shawn's landing page)

2024-12-11 21:53 UTC, ShawnAviles commented on src/pages/api/announcements/create.ts
> +import { createAnnouncement } from "../../../data/annoucementData";
NIT: we have alias for src directory setup (`@`) so this should be `@/data/announcements` same thing on every other page

2024-12-11 21:54 UTC, ShawnAviles approved these changes
Tested Locally and LGTM 👍

2024-12-11 22:04 UTC, Caposto requested changes

2024-12-11 22:04 UTC, Caposto commented on src/data/annoucementData.ts
> +export async function createAnnouncement(
Should we implement, try-catch pattern here? Ik running it in the server returned error but not sure how we want to display them to the users

2024-12-12 19:13 UTC, Caposto approved these changes

2024-12-12 21:27 UTC, merged